### ISSUE TITLE
Error Handling Signatures

### ISSUE THREAD

**Issue by AngelMunoz** [fable-compiler/fable-promise#13]
I was looking at some compiled JS code (due to a bug I had on a "catch" clause) and found out  interestingly that fable-promise uses the form `.then(success, error)` way of handle exceptions
https://github.com/fable-compiler/fable-promise/blob/master/src/Promise.fs#L35-L45

usually the preferred form (afaik) is 

`.then(success).catch(error)` 

since this will allow exception bubbling (i.e. pass the exception to the next catch handler in the chain and so on until you get to the last) even if there's a throw inside .catch which sometimes is useful a graceful recovery and continue with async operations.

when you use `.then(success, error)` if the success handler throws or is rejected, the error handler will not be invoked, this rejection will be sent to the next `.catch` on the promise chain

I got an example here 

https://codesandbox.io/s/promise-errors-cf439?file=/src/index.js

let me know if this is something we can look into I can try to save some time and send a PR later on

> Some reading stuff on the matter (the first one is my always go-to resource)
> https://pouchdb.com/2015/05/18/we-have-a-problem-with-promises.html (tl;dr <small>Advanced mistake 2</small>)
> https://dmitripavlutin.com/javascript-promises-then-vs-then-catch/#2-whats-the-difference

**Comment by alfonsogarciacaro** [comment]
I didn't remember exactly the reason but checking the old fable-powerpack repo I found this issue: https://github.com/fable-compiler/fable-powerpack/issues/26

So basically the reason was to support fable-promise with implementations that only covered `.then`. Not sure if this is an issue nowadays, it's probably ok to use `.catch`.

**Comment by MangelMaxime** [comment]
Hum, this could explained a lot of issues I got recently when working with a promise based library to communicate with my database.

**Comment by baronfel** [comment]
In order to make other types opt-in-able to `JS.Promise` as exposed here, I think this library should ship a `Source` member for `JS.Promise`.  What this would do is easily allow other libraries to integrate their thenable typed values with the `promise` CE, like I've manually done in Ionide [here](https://github.com/baronfel/ionide-vscode-fsharp/blob/terminal-provider/src/Core/Utils.fs#L18-L20).

Would using this mechanism clear up any of this issue, or am I conflating different things here?

**Comment by AngelMunoz** [comment]
it's a different issue, but it should allows us to enable `.catch` and keep supporting thenables
do you know where's the `Thenable<'T>` definition @baronfel ? I will play with some code and see if it doesn't break stuff

**Comment by baronfel** [comment]
Thenable will likely be defined in many different places, that's why the Source member is so important: it allows users of this package to add their own overloads and opt in to the promise CE behavior.

**Comment by baronfel** [comment]
For reference though, the vscode-defined Thenable is [here](https://github.com/ionide/ionide-vscode-helpers/pull/39/files#diff-65aa5c7f3e87d62056b982b9e46d477bd28896ec90be108691ea10a94e392666R7803-R7808)

**Comment by MangelMaxime** [comment]
Closing this issue as version 3.0.0-beta-001 contains the fixes and it should soon be released as stable.

#20
