### ISSUE TITLE
return! failwithf is broken in latest version

### ISSUE THREAD

**Issue by forki** [fable-compiler/fable-promise#21]
![image](https://user-images.githubusercontent.com/57396/133567118-971e39fb-91c3-43e5-8d41-0cdb5c5ac721.png)

`/home/gitlab-runner/builds/d5cd2d2a/0/a-team/eCarApp/src/Client/Utils.fs(42,22): error FS0041: Eine eindeutige Überladung für Methode 'Source' konnte nicht auf Basis von Typinformationen vor diesem Programmpunkt bestimmt werden. Unter Umständen ist eine Typanmerkung erforderlich.Bekannter Argumenttyp: 'aKandidaten: - member Promise.PromiseBuilder.Source : p:Fable.Core.JS.Promise<'T1> -> Fable.Core.JS.Promise<'T1> - member Promise.PromiseBuilder.Source : ps:'a0 -> 'a0 when 'a0 :> seq<'a1> [/home/gitlab-runner/builds/d5cd2d2a/0/a-team/eCarApp/test/ComponentTests/ComponentTests.fsproj]`

It says it wants a type hint. Why is that? This used to work.

**Comment by forki** [comment]
Downgrade to Fable.Promise 2.2.2 seems make it work again

**Comment by MangelMaxime** [comment]
This is related this PR https://github.com/fable-compiler/fable-promise/pull/15

Adding the `Source` member allows to support Promise compatible types by extending the library but the F# compiler is a bit more picky on the type inference on some cases.

Alfonso had a similar problem in his project https://github.com/fable-compiler/fable-promise/pull/15#issuecomment-912171487

**Comment by alfonsogarciacaro** [comment]
This was what I was afraid of :/ that the new version would break projects and the fix wouldn't be obvious. And we cannot say @forki has little experience with F# ;) I published the 3.0 because the conclusion of the discussion #15 seemed to be in favor of keeping the `Source` feature and because there were no complains about the beta release (but of course people don't upgrade to a beta unless there's a strong reason for it).

I still think that the annoyance these errors will cause users outweighs the benefit of adding `Source` to the computation expression (and I'm still unsure even Ionide would benefit strongly of it). It's not nice to remove a feature after the _stablish_ version has been released, but maybe we're in time of unlisting 3.0 and publish 3.1 without it. But I need some support for the decision ;) ...@forki?

**Comment by forki** [comment]
I didn't read the details (yet) - just from a general POV: breaking `return! failwithf` is a real issue for us. We use it everywhere.

**Comment by MangelMaxime** [comment]
Looking at #15 

It seems like replacing `return! failwith` with `return failwith` should works:

https://github.com/fable-compiler/fable-promise/pull/15/files#diff-abf2407c355c2c7c7dd4f3ef6213df319cf9594f945e9ec7941cbcbb0183968cL147-L157

@alfonsogarciacaro 

I also had an idea on how to not have a breaking change and still have support for promise-like.

My ideas was to hide the `Source` extensions behind a module meaning that by default it is not active but if the user write `open Promise.Extension` (meaning it know that he is using advanced usage) then it become active.

See #22

**Comment by forki** [comment]
tbf I can live with `return failwithf` without the bang. @dsyme showed me `return! failwith` long long time ago, but I *think* it's basically the same

**Comment by MangelMaxime** [comment]
Personally, I just checked and in my code base I only use `return failwith` from the beginning that's probably why I didn't have this issue.

In my head, the logic is that `failwith` return a **value** and not a **promise containing a value** so I use `return`.

**Comment by forki** [comment]
"Showing 50 changed files with 137 additions and 137 deletions" ;-)

**Comment by alfonsogarciacaro** [comment]
Fable.Promise 3.1 removes `Source` because it can be added as an extension for users who need it, so hopefully this issue should be fixed 👍
